# Generated by Django 3.2.12 on 2022-04-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('manufacturer', models.CharField(max_length=256, verbose_name='Manufacturer')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Price')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Old Price')),
                ('image', models.ImageField(upload_to='product-images', verbose_name='Image')),
                ('sold_out', models.BooleanField(default=False, verbose_name='Sold out')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('position', models.IntegerField(help_text='1 - higher priority ', verbose_name='Position')),
            ],
            options={
                'ordering': ('position', 'date_uploaded'),
            },
        ),
    ]
