# Generated by Django 3.2.12 on 2022-04-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='asd', unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
