# Generated by Django 3.2.8 on 2022-04-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220420_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.IntegerField(blank=True, help_text='1 - higher priority ', null=True, verbose_name='Position'),
        ),
    ]
