# Generated by Django 3.2.8 on 2022-04-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220420_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.BooleanField(blank=True, default=False, help_text='Check this if item is used', null=True),
        ),
    ]
