# Generated by Django 3.2.8 on 2022-04-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220420_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('used', 'Used'), ('new', 'New')], default=('new', 'New'), max_length=120, null=True),
        ),
    ]
