# Generated by Django 3.2.8 on 2022-04-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('used', 'Used'), ('new', 'New')], default='new', max_length=120),
        ),
    ]
