# Generated by Django 3.2.12 on 2022-04-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Caliber',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Caliber'),
        ),
        migrations.AddField(
            model_name='product',
            name='Case_Material',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Case Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='Case_size',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Case size'),
        ),
        migrations.AddField(
            model_name='product',
            name='Clock_face',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Clock-face'),
        ),
        migrations.AddField(
            model_name='product',
            name='Comments_to_the_color',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Comments to the color'),
        ),
        migrations.AddField(
            model_name='product',
            name='Features',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='product',
            name='Functions',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Functions'),
        ),
        migrations.AddField(
            model_name='product',
            name='Gender',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='product',
            name='Glass',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Glass'),
        ),
        migrations.AddField(
            model_name='product',
            name='Mechanism',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Mechanism'),
        ),
        migrations.AddField(
            model_name='product',
            name='Power_reserve',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Power reserve'),
        ),
        migrations.AddField(
            model_name='product',
            name='Ref',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Ref'),
        ),
        migrations.AddField(
            model_name='product',
            name='Strap',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Strap'),
        ),
        migrations.AddField(
            model_name='product',
            name='The_case_shape',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='The case shape'),
        ),
        migrations.AddField(
            model_name='product',
            name='Water_resistance',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Water resistance'),
        ),
    ]
