# Generated by Django 3.2.12 on 2022-04-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220422_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Comments_to_the_strap',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Strap'),
        ),
        migrations.AddField(
            model_name='product',
            name='Dial_colour',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Dial_colour'),
        ),
    ]
