# Generated by Django 3.2.12 on 2022-04-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220422_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Comments_to_the_strap',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Comments to the strap\t'),
        ),
    ]
