# Generated by Django 3.2.12 on 2022-04-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_product_comments_to_the_strap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Case_Material',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Comments_to_the_strap',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Strap',
        ),
        migrations.AddField(
            model_name='product',
            name='Additionally',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Additionally'),
        ),
        migrations.AddField(
            model_name='product',
            name='Bezel_material',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Bezel material'),
        ),
        migrations.AddField(
            model_name='product',
            name='Box',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Box'),
        ),
        migrations.AddField(
            model_name='product',
            name='Bracelet_color',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Bracelet/strap color'),
        ),
        migrations.AddField(
            model_name='product',
            name='Bracelet_material',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Bracelet/strap material'),
        ),
        migrations.AddField(
            model_name='product',
            name='Bracelet_strap',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Bracelet/strap'),
        ),
        migrations.AddField(
            model_name='product',
            name='Case_diameter',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Case diameter'),
        ),
        migrations.AddField(
            model_name='product',
            name='Case_material',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Case material'),
        ),
        migrations.AddField(
            model_name='product',
            name='Clasp_Fold_clasp',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Clasp Fold clasp'),
        ),
        migrations.AddField(
            model_name='product',
            name='Clasp_material',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Clasp material'),
        ),
        migrations.AddField(
            model_name='product',
            name='Crystal',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Crystal'),
        ),
        migrations.AddField(
            model_name='product',
            name='Dial',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Dial'),
        ),
        migrations.AddField(
            model_name='product',
            name='Dial_blue',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Dial Blue'),
        ),
        migrations.AddField(
            model_name='product',
            name='Dial_numerals',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Dial numerals'),
        ),
        migrations.AddField(
            model_name='product',
            name='Guarantee',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Guarantee'),
        ),
        migrations.AddField(
            model_name='product',
            name='Location',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='product',
            name='Movement',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Movement'),
        ),
        migrations.AddField(
            model_name='product',
            name='Movement_Caliber',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Movement/Caliber'),
        ),
        migrations.AddField(
            model_name='product',
            name='Note',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Note'),
        ),
        migrations.AddField(
            model_name='product',
            name='Number_of_jewels',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Number of jewels'),
        ),
        migrations.AddField(
            model_name='product',
            name='Specifications',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Specifications'),
        ),
        migrations.AddField(
            model_name='product',
            name='Thickness',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Thickness'),
        ),
        migrations.AddField(
            model_name='product',
            name='Total_height',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Total height'),
        ),
        migrations.AddField(
            model_name='product',
            name='Year_of_production',
            field=models.CharField(blank=True, default=' ', max_length=256, null=True, verbose_name='Year of production'),
        ),
    ]
