# Generated by Django 3.2.12 on 2022-05-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220501_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description_ge',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='Description_ru',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
