# Generated by Django 3.2.12 on 2022-05-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220502_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description_en'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description_ge',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description_ge'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Description_ru',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description_ru'),
        ),
    ]
