# Generated by Django 3.2.12 on 2022-05-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_productdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='description_en',
            new_name='desc_en',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='description_ge',
            new_name='desc_ge',
        ),
        migrations.RenameField(
            model_name='productdetails',
            old_name='description_ru',
            new_name='desc_ru',
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_desc', to='main.product'),
        ),
    ]
